# DATABASE
spring:
  environment: "local"
  profiles:
    active: ${activeProfile:dev}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: always

  thymeleaf:
    prefix: "classpath:/templates/"
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
    output:
      ansi:
        enabled: always

custom:
  tossPayments:
    secretKey: "test_sk_dP9BRQmyarYaNnnkNDXrJ07KzLNk"
    clientKey: "test_ck_OyL0qZ4G1VOEJZvgGKw8oWb2MQYg"

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false





