# DATABASE
spring:
  profiles:
    active: ${activeProfile:dev}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  output:
    ansi:
      enabled: always

  thymeleaf:
    prefix: "classpath:/templates/"
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


custom:
  tossPayments:
    secretKey: "test_sk_dP9BRQmyarYaNnnkNDXrJ07KzLNk"
    clientKey: "test_ck_OyL0qZ4G1VOEJZvgGKw8oWb2MQYg"




